# Generated by Django 6.0.2 on 2026-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=50)),
                ('questions_answered', models.IntegerField(default=0)),
                ('questions_correct', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('session_id', 'topic')},
            },
        ),
    ]
